export function createDom() {
  const dom = {
    codeInput: document.querySelector("#code-input"),
    codeEditorHost: document.querySelector("#code-editor-host"),
    codeEditorShell: document.querySelector("#editor-code-shell"),
    topbarTitle: document.querySelector("#topbar-title"),
    projectsButton: document.querySelector("#projects-button"),
    settingsButton: document.querySelector("#settings-button"),
    workspaceMain: document.querySelector(".workspace-main"),
    workspaceKicker: document.querySelector("#workspace-kicker"),
    workspaceRefreshButton: document.querySelector("#workspace-refresh"),
    workspaceRail: document.querySelector("#workspace-rail"),
    workspaceSortSelect: document.querySelector("#workspace-sort"),
    workspaceTree: document.querySelector("#workspace-tree"),
    workspaceEmpty: document.querySelector("#workspace-empty"),
    workspaceContextMenu: document.querySelector("#workspace-context-menu"),
    contextNewMermaidFileButton: document.querySelector("#context-new-mermaid-file"),
    contextNewDrawioFileButton: document.querySelector("#context-new-drawio-file"),
    contextNewFolderButton: document.querySelector("#context-new-folder"),
    contextRenameButton: document.querySelector("#context-rename"),
    contextDeleteButton: document.querySelector("#context-delete"),
    newDocumentButton: document.querySelector("#new-document"),
    newDrawioDocumentButton: document.querySelector("#new-drawio-document"),
    copyCodeButton: document.querySelector("#copy-code"),
    paneDivider: document.querySelector("#pane-divider"),
    editorEyebrow: document.querySelector("#editor-eyebrow"),
    editorDocumentSuffix: document.querySelector("#editor-document-suffix"),
    drawioShell: document.querySelector("#drawio-shell"),
    drawioHost: document.querySelector("#drawio-host"),
    preview: document.querySelector("#preview"),
    previewCompare: document.querySelector("#preview-compare"),
    previewBefore: document.querySelector("#preview-before"),
    previewAfter: document.querySelector("#preview-after"),
    previewBeforeLabel: document.querySelector("#preview-before-label"),
    previewAfterLabel: document.querySelector("#preview-after-label"),
    previewBeforeZoomOutButton: document.querySelector("#preview-before-zoom-out"),
    previewBeforeZoomFitButton: document.querySelector("#preview-before-zoom-fit"),
    previewBeforeZoomInButton: document.querySelector("#preview-before-zoom-in"),
    previewAfterZoomOutButton: document.querySelector("#preview-after-zoom-out"),
    previewAfterZoomFitButton: document.querySelector("#preview-after-zoom-fit"),
    previewAfterZoomInButton: document.querySelector("#preview-after-zoom-in"),
    previewBody: document.querySelector(".preview-body"),
    previewFrame: document.querySelector("#preview-frame"),
    previewEmpty: document.querySelector("#preview-empty"),
    previewEyebrow: document.querySelector("#preview-eyebrow"),
    statusBadge: document.querySelector("#status-badge"),
    statusText: document.querySelector("#status-text"),
    encodingStatus: document.querySelector("#encoding-status"),
    cursorStatus: document.querySelector("#cursor-status"),
    copyClipboardButton: document.querySelector("#copy-clipboard"),
    exportButton: document.querySelector("#export-button"),
    exportMenu: document.querySelector("#export-menu"),
    exportDrawioButton: document.querySelector("#export-drawio"),
    exportPptxButton: document.querySelector("#export-pptx"),
    exportSvgButton: document.querySelector("#export-svg"),
    exportPngButton: document.querySelector("#export-png"),
    exportJpgButton: document.querySelector("#export-jpg"),
    zoomInButton: document.querySelector("#zoom-in"),
    zoomOutButton: document.querySelector("#zoom-out"),
    zoomFitButton: document.querySelector("#zoom-fit"),
    previewCanvasTools: document.querySelector(".preview-canvas-tools"),
    topbarWorkspacePath: document.querySelector("#topbar-workspace-path"),
    editorDocumentName: document.querySelector("#editor-document-name"),
    settingsModal: document.querySelector("#settings-modal"),
    settingsBackdrop: document.querySelector("#settings-backdrop"),
    settingsCloseButton: document.querySelector("#settings-close"),
    settingsCancelButton: document.querySelector("#settings-cancel"),
    settingsSaveButton: document.querySelector("#settings-save"),
    settingsEyebrow: document.querySelector("#settings-eyebrow"),
    settingsTitle: document.querySelector("#settings-title"),
    settingsTablist: document.querySelector("#settings-tablist"),
    settingsTabGeneral: document.querySelector("#settings-tab-general"),
    settingsTabAi: document.querySelector("#settings-tab-ai"),
    settingsContent: document.querySelector("#settings-content"),
    settingsPanelGeneral: document.querySelector("#settings-panel-general"),
    settingsPanelAi: document.querySelector("#settings-panel-ai"),
    settingsLanguageTitle: document.querySelector("#settings-language-title"),
    settingsLanguageLabel: document.querySelector("#settings-language-label"),
    settingsLanguageSelect: document.querySelector("#settings-language-select"),
    settingsThemeTitle: document.querySelector("#settings-theme-title"),
    settingsOfficialThemeField: document.querySelector("#settings-official-theme-field"),
    settingsThemeLabel: document.querySelector("#settings-theme-label"),
    settingsThemeSelect: document.querySelector("#settings-theme-select"),
    themeModeOfficialButton: document.querySelector("#theme-mode-official"),
    themeModeCustomButton: document.querySelector("#theme-mode-custom"),
    settingsCustomPanel: document.querySelector("#settings-custom-panel"),
    settingsCustomConfigLabel: document.querySelector("#settings-custom-config-label"),
    settingsCustomConfig: document.querySelector("#settings-custom-config"),
    settingsClipboardTitle: document.querySelector("#settings-clipboard-title"),
    settingsClipboardLabel: document.querySelector("#settings-clipboard-label"),
    settingsClipboardFormat: document.querySelector("#settings-clipboard-format"),
    settingsAiTitle: document.querySelector("#settings-ai-title"),
    settingsAiPromptsTitle: document.querySelector("#settings-ai-prompts-title"),
    settingsAiEnabledLabel: document.querySelector("#settings-ai-enabled-label"),
    settingsAiEnabled: document.querySelector("#settings-ai-enabled"),
    settingsAiBaseUrlLabel: document.querySelector("#settings-ai-base-url-label"),
    settingsAiBaseUrl: document.querySelector("#settings-ai-base-url"),
    settingsAiModelLabel: document.querySelector("#settings-ai-model-label"),
    settingsAiModel: document.querySelector("#settings-ai-model"),
    settingsAiTokenLabel: document.querySelector("#settings-ai-token-label"),
    settingsAiToken: document.querySelector("#settings-ai-token"),
    settingsAiSystemPromptLabel: document.querySelector("#settings-ai-system-prompt-label"),
    settingsAiSystemPrompt: document.querySelector("#settings-ai-system-prompt"),
    settingsAiUserPromptLabel: document.querySelector("#settings-ai-user-prompt-label"),
    settingsAiUserPrompt: document.querySelector("#settings-ai-user-prompt"),
    settingsAiPromptNote: document.querySelector("#settings-ai-prompt-note"),
    settingsAiTokenStatus: document.querySelector("#settings-ai-token-status"),
    settingsAiTestButton: document.querySelector("#settings-ai-test"),
    settingsAiClearToken: document.querySelector("#settings-ai-clear-token"),
    settingsAiTestStatus: document.querySelector("#settings-ai-test-status"),
    aiButton: document.querySelector("#ai-button"),
    aiInlinePanel: document.querySelector("#ai-inline-panel"),
    aiInlineKicker: document.querySelector("#ai-inline-kicker"),
    aiInlineTitle: document.querySelector("#ai-inline-title"),
    aiInlineModePill: document.querySelector("#ai-inline-mode-pill"),
    aiInlinePromptLabel: document.querySelector("#ai-inline-prompt-label"),
    aiInlinePromptInput: document.querySelector("#ai-inline-prompt-input"),
    aiInlineGenerateButton: document.querySelector("#ai-inline-generate"),
    aiInlineStatusChip: document.querySelector("#ai-inline-status-chip"),
    aiInlineStatusText: document.querySelector("#ai-inline-status-text"),
    aiInlineError: document.querySelector("#ai-inline-error"),
    aiInlineThinkingPanel: document.querySelector("#ai-inline-thinking-panel"),
    aiInlineThinkingLabel: document.querySelector("#ai-inline-thinking-label"),
    aiInlineThinkingText: document.querySelector("#ai-inline-thinking-text"),
    aiInlineFooter: document.querySelector(".ai-inline-footer"),
    aiInlineAdjustButton: document.querySelector("#ai-inline-adjust"),
    aiInlineRejectButton: document.querySelector("#ai-inline-reject"),
    aiInlineAcceptButton: document.querySelector("#ai-inline-accept"),
    aiModal: document.querySelector("#ai-modal"),
    aiBackdrop: document.querySelector("#ai-backdrop"),
    aiCloseButton: document.querySelector("#ai-close"),
    aiEyebrow: document.querySelector("#ai-eyebrow"),
    aiTitle: document.querySelector("#ai-title"),
    aiModeNewButton: document.querySelector("#ai-mode-new"),
    aiModeMergeButton: document.querySelector("#ai-mode-merge"),
    aiContextNote: document.querySelector("#ai-context-note"),
    aiPromptLabel: document.querySelector("#ai-prompt-label"),
    aiPromptInput: document.querySelector("#ai-prompt-input"),
    aiGenerateButton: document.querySelector("#ai-generate"),
    aiStatusChip: document.querySelector("#ai-status-chip"),
    aiStatusText: document.querySelector("#ai-status-text"),
    aiResultSection: document.querySelector("#ai-result-section"),
    aiResultKicker: document.querySelector("#ai-result-kicker"),
    aiResultTitle: document.querySelector("#ai-result-title"),
    aiResultSummary: document.querySelector("#ai-result-summary"),
    aiCodePanelTitle: document.querySelector("#ai-code-panel-title"),
    aiModelPill: document.querySelector("#ai-model-pill"),
    aiResultCode: document.querySelector("#ai-result-code"),
    aiDiffPanel: document.querySelector("#ai-diff-panel"),
    aiDiffPanelTitle: document.querySelector("#ai-diff-panel-title"),
    aiDiffSummary: document.querySelector("#ai-diff-summary"),
    aiDiffBeforeLabel: document.querySelector("#ai-diff-before-label"),
    aiDiffBefore: document.querySelector("#ai-diff-before"),
    aiDiffAfterLabel: document.querySelector("#ai-diff-after-label"),
    aiDiffAfter: document.querySelector("#ai-diff-after"),
    aiErrorMessage: document.querySelector("#ai-error-message"),
    aiCancelButton: document.querySelector("#ai-cancel"),
    aiCopyButton: document.querySelector("#ai-copy"),
    aiApplyButton: document.querySelector("#ai-apply")
  };

  dom.previewCompareBeforeCard = dom.previewBefore?.closest(".preview-compare-card") ?? null;
  dom.previewCompareAfterCard = dom.previewAfter?.closest(".preview-compare-card") ?? null;
  dom.exportMenuItems = [
    dom.exportDrawioButton,
    dom.exportPptxButton,
    dom.exportSvgButton,
    dom.exportPngButton,
    dom.exportJpgButton
  ];
  dom.workspaceContextMenuItems = [
    dom.contextNewMermaidFileButton,
    dom.contextNewDrawioFileButton,
    dom.contextNewFolderButton,
    dom.contextRenameButton,
    dom.contextDeleteButton
  ];

  return dom;
}
